name: Deploy Ecom UI to UAT

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: uat

    env:
      IP: ${{ vars.IP }}
      SERVER_LOCATION: ${{ vars.SERVER_LOCATION }}
      TEAMS_WEBHOOK_URL: ${{ vars.TEAMS_WEBHOOK_URL }}
      GITHUB_SHA: ${{ github.sha }}
      GITHUB_ACTOR: ${{ github.actor }}
      ECR_REPOSITORY: ecom-ui-uat
      IMAGE_TAG: latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install dependencies
        run: |
          rm package-lock.json
          npm install

      - name: Build
        run: npm run build-uat

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Enable Docker layer caching
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image to ECR
        uses: docker/build-push-action@v7
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          cache-from: type=registry,ref=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
          cache-to: type=inline

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PROENX_SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: ssh-keyscan -H $IP >> ~/.ssh/known_hosts

      - name: Redeploy on cluster
        run: |
          ssh $SERVER_LOCATION 'kubectl delete -f /home/centos/ecom-ui/deploy.yml || true'
          ssh $SERVER_LOCATION 'kubectl apply  -f /home/centos/ecom-ui/deploy.yml'

      - name: Notify Teams
        run: |
          curl -d "{\"text\":\"Ecom UI deployed in UAT.\nCommit: $GITHUB_SHA\nBy: $GITHUB_ACTOR\"}" -H "Content-Type:application/json" "$TEAMS_WEBHOOK_URL"
